pretrained_name: "facebook/bart-base"
vocab_size: 50265
max_position_embeddings: 1024
model_type: "bart"
normalize_before: false
normalize_embedding: true
scale_embedding: false
add_final_layer_norm: false
add_bias_logits: false
activation_function: "gelu"
d_model: 768
is_encoder_decoder: true
encoder_layers: 6
encoder_attention_heads: 12
encoder_ffn_dim: 3072
decoder_layers: 6
decoder_attention_heads: 12
decoder_ffn_dim: 3072
dropout: 0.0
attention_dropout: 0.0
activation_dropout: 0.0
encoder_layerdrop: 0.0
decoder_layerdrop: 0.0
init_std: 0.01
gradient_checkpointing: false
# generation
decoder_start_token_id: 2
bos_token_id: 0
eos_token_id: 2
pad_token_id: 1
forced_eos_token_id: 2
use_cache: True
# memory
memory_len: 64
# use_return_dict: True